// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxhfmmrywxhfwulnkqgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4aGZtbXJ5d3hoZnd1bG5rcWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTY4MTgsImV4cCI6MjA2NTgzMjgxOH0.C_EPF1AQEC1FgEZMcyjtVMJCxjqCBDfkw44r7DKDYdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});